name: ecosort
description: EcoSort - Waste Detection (Glass & Paper)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  tflite_flutter: ^0.12.1

  image_picker: ^1.0.4
  image: ^4.1.3
  google_maps_flutter: ^2.7.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/recycle_logo.png
    - assets/images/h1.jpg
    - assets/images/h2.jpeg
    - assets/images/h3.png
    - assets/images/h4.png
    - assets/images/bins.png
    - assets/images/h5.png
    - assets/model/model.tflite
    - assets/model/labels.txt
    - assets/data/diy_tips.json
